# What is NUMPY -
- Numpy is the fundamental package for scientific computing in python. 
- It is a python library that provides a MULTIDIMENSIONAL ARRAY OBJECT, various derived objects 
(such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including 
mathmetical, logical, shape manipulation, sorting, selection, I/O, discrete Fourier Transforms, basic Linear Algebra
Basic Statistical operations , Random Simulation and much more.
- Basically Nummpy is a Scientific computing library that provides "Numpy Arrays". With help of Numpy arrays other objects created like "Matrices" , "Masked arrays" and "Structured arrays on which Numpy provide some functionality which can be used such as "Mathmetical Functions", "Imput-Output", "sortings", "Selection Functions" and "Linear Algebra related functions, "Statistics related Functions".

- At the core of Numpy Package, is the NDARRAY OBJECT. This encapsulation n-dimensional arrays of HOMOGENEOUS DATA TYPES


# What is the need of "NUMPY" -
## When we have "LIST" in "Python" then what is the need to create "Numpy" :

- In 2008, when Data Science and Machine Learning were gaining traction, Matlab and R were indeed popular tools for data analysis and machine learning tasks. Python was not as widely used for these purposes at the time. One of the main reasons for this was that Python's native data types like lists and dictionaries were not as efficient for handling large datasets commonly encountered in machine learning. 
- However, the situation changed with the introduction of the "Numpy" package. Numpy is a fundamental package for scientific computing in Python. It provides support for large, multi-dimensional arrays and matrices, along with an extensive collection of mathematical functions to operate on these arrays. The crucial aspect of Numpy is that it is written in C language, which makes it fast and efficient, especially when handling large datasets.
- The popularity of Numpy grew quickly due to its efficient array processing capabilities, and it became the foundation for many other libraries in the Python data science ecosystem. Other libraries, such as "Pandas" and "Scikit-learn," were built on top of Numpy. 
- The combination of Python's easy-to-understand syntax and the efficiency of Numpy arrays made Python a powerful and accessible language for data science and machine learning tasks. Over time, Python has become the de facto language for many data scientists and machine learning practitioners due to the growth of its ecosystem, the ease of use, and the availability of various libraries built upon Numpy.

# NUMPY ARRAY VS PYTHON SEQUENCES

- Numpy Arrays have a fixed size at creation, unlike Python LISTS(which can grow dynamically)
- changing the size of an ndarray will create a new array and delete the original.

- The elements in a Numpy Array are all required to be of the same data type, and thus will be the same size in memory.
- Numpy arrays facilitate advanced mathematical and other types of operations on large number of data.
- Typically, such operations are executed more efficiently and with less code than is possible using pythons built in sequences.

- A growing plethora of scientific and mathematical python based packages are using NumpyArrays; though these typically support
python sequence input, they convert such input to Numpy arrays prior to processing, and they often output numpy arrays.

In [2]:
import numpy as np

# N- D arrays
its homogenous
Fixed itemsize


# Creating N- D Arrays

''' 
1- using np.array(1D, 2 D) 

2- np.zeros/ones/empty/random()

3- np.arange()

4- np.linspace()

5- copy()

6- identity() 
'''

#creating numpy / n-d array

# For including numpy firstly we need to import numpy library into our code.

# Numpy arrays take list when we create an array with np.array

In [3]:
# 1 D ARRAY / Vector
arr1 = np.array([1,2,3,4,5,])

In [4]:
print(arr1)

[1 2 3 4 5]


In [5]:
type(arr1)

numpy.ndarray

In [6]:
# 2d array / Metrices

arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
type(arr2)

numpy.ndarray

In [15]:
arr3 = np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
# 3 d array / Tensor

c  = np.array([[[1,2], [3,4]], [[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [10]:
# dttype
np.array([1,2,3], dtype = float)

array([1., 2., 3.])

In [11]:
# dttype
np.array([1,2,3], dtype = bool)

array([ True,  True,  True])

In [14]:
# dttype
np.array([1,2,3], dtype = complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

# np.ones and np.zeros - here we need to provide tuple - intialize technique
- it use in neural networks 

In [17]:
arr4 = np.ones((3,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# np.identity helps in create identity matrix
- its digonal item is - 1, all other item is - 0

In [25]:
arr5 = np.identity(5)
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# np.random generate random numbers - intialize technique

In [22]:
np.random.random((3,5))

array([[0.49099832, 0.50144629, 0.19521973, 0.27136682, 0.58392896],
       [0.82154803, 0.8103869 , 0.28917675, 0.2491503 , 0.5051373 ],
       [0.72481902, 0.15002906, 0.06539541, 0.25698849, 0.29374583]])

# np.arange - first include last not include, range can also given
- range is a built-in Python class, while arange() is a function that belongs to a third-party library (NumPy).

In [20]:
arr6 = np.arange(10)  # counterfunction of range 
arr6

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
arr7 = np.arange(5,15)
arr7

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [22]:
arr8 = np.arange(5,15,2)
arr8

array([ 5,  7,  9, 11, 13])

# np.arange with reshape - it use to convert array in any shape
- it will work only when product should be equal to number of item inside the array.

In [15]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [16]:
np.arange(1,13).reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

# np.linspace (linearly space)
- in this  we provide range 3 things - range (lower, upper, step)
- it in given range generate point in equal distance

In [20]:
arr7 = np.linspace(10,20,10) #lower , upper, jump
arr7

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [21]:
arr8 = arr7.copy()
arr8

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

# Numpy Properties &  ARRAY Attributes
- ndim, shape, size, itemsize, dtype

In [27]:
a1 = np.arange(10)
a2 = np.arange(12, dtype = float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [28]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [30]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

# 1- ndim 
- number of dimension.
- for finding dimension of array we can use ndim.
- it will tell array is 1d , 2d or 3d.

In [31]:
a1.ndim

1

In [32]:
a2.ndim

2

In [33]:
a3.ndim

3

# 2- shape 
- it shows in every dimension how many items.
- how many rows and how many columns

In [34]:
a1.shape

(10,)

In [35]:
a2.shape

(3, 4)

In [36]:
a3.shape

(2, 2, 2)

# 3- Size 
- it will tell number of items in array

In [37]:
a2.size # 12 items in a2

12

In [38]:
a3.size

8

# 4 - Itemsize
- it will tell every items occupy how much space in memmory.
- same data type occupy same space.
- as in example a2, a3 are occupying 8 bit size as both are int64.

In [41]:
a2.itemsize # it means taking 8 byte space. it using int64 for memory filing.

8

In [40]:
a3.itemsize

8

# 5- dtype
- it tell what is your item data type


In [42]:
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
float64
int64


# changing Data Type 
- we do for saving memory by changing data type 

# 1- astype

In [44]:
a3
print(a3.dtype)

int64


In [45]:
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

In [47]:
a3.dtype # we changed int64 in int32 as no need to save in big memory

dtype('int64')

# comparison of Numpy and list
-  NUMPY ARRAY ARE FASTER 
- numpay are convenient
- numpy take less memory
- for checking we use time library to prove my point

In [79]:
lista = range(100)
print(lista)

range(0, 100)


In [80]:
arr11= np.arange(100)
arr11

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [82]:
import sys
# calling get.sizeof function for finding real time 

In [83]:
print(sys.getsizeof(87)*len(lista)) # 87 is any random nu bw 100 no in list

2800


In [85]:
print(arr11.itemsize*arr11.size)  #itemsize give one item and size will give overall no size

800


In [86]:
# hence proved list take 2800 memory and array took 800 array

In [88]:
import time   # for measuring speed use time 

In [99]:
x = range(10000000)
y = range(10000000, 20000000)

start_time = time.time() # it will give current time
c = [(x,y) for x, y in zip(x,y)]  #zip will take one item and store in variable c 

print(time.time()- start_time)  # time se current time min will give code running timing

1.8905739784240723


In [101]:
a = np.arange(10000000)
b = np.arange(10000000,20000000)
start_time = time.time()
c= a+b
print(time.time()- start_time)

0.02451491355895996


# NUMPY OPERATIONS
- we can apply mathmetical operation on numpy array.

In [48]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

In [49]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [51]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# 1- Scalar operation - on single array do application with math
# airthmetic

In [52]:
a1 *2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [56]:
a1 /3

array([[0.        , 0.33333333, 0.66666667, 1.        ],
       [1.33333333, 1.66666667, 2.        , 2.33333333],
       [2.66666667, 3.        , 3.33333333, 3.66666667]])

In [55]:
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [57]:
a1 + 2

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [58]:
a1 - 4

array([[-4, -3, -2, -1],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7]])

# 2 - Relational Operators
- it compare with every item in array and give output in true and false

In [59]:
a2 > 5

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [60]:
a3 < 6

array([[[ True,  True],
        [ True,  True]],

       [[ True,  True],
        [False, False]]])

In [62]:
a2 == 14

array([[False, False,  True, False],
       [False, False, False, False],
       [False, False, False, False]])

# VECTOR OPERATIONS
# AIRTHMETIC

In [63]:
a1 * a2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [64]:
a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

 # Numpy Array Functions (all mathmetical function)

In [68]:
a1 = np.random.random((3,3))
a1 = np.round(a1 * 100)
a1

array([[80., 47., 77.],
       [91., 42., 39.],
       [25., 31., 24.]])

# 1 - max/min/sum/product
#### 0 means - column,  1 means rows in NUMPY

- np.max will give maximum item
- np.min will give minimum item
- np.sum will give sum of all item
- np.prod will give multiplication of all number

In [69]:
np.max(a1)

91.0

In [70]:
np.min(a1)

24.0

In [71]:
np.sum(a1)

456.0

In [72]:
np.prod(a1)

802688062176000.0

In [73]:
# we can do this axis or dimension wise fucntion application

In [74]:
np.max(a1, axis = 1) # so for every row it given max number

array([80., 91., 31.])

In [76]:
np.max(a1, axis = 0) # axis = 0 it will give max number based on column vise.

array([91., 47., 77.])

In [77]:
np.prod(a1, axis = 1)

array([289520., 149058.,  18600.])

# 2 - MEAN/ MEDIAN/ STD/ VAR - statistical operation

In [78]:
a1

array([[80., 47., 77.],
       [91., 42., 39.],
       [25., 31., 24.]])

In [79]:
np.mean(a1,axis= 1)

array([68.        , 57.33333333, 26.66666667])

In [80]:
np.median(a1, axis = 1)

array([77., 42., 25.])

In [81]:
np.var(a1, axis = 1)

array([222.        , 568.22222222,   9.55555556])

In [82]:
np.std(a1, axis = 1)

array([14.89966443, 23.83741224,  3.09120617])

# 3 - Trignoetric function 
- not very useful in Data Science

In [84]:
np.sin(a1)

array([[-0.99388865,  0.12357312,  0.99952016],
       [ 0.10598751, -0.91652155,  0.96379539],
       [-0.13235175, -0.40403765, -0.90557836]])

# 4 - DOT PRODUCT
- it is very useful.
- we find dot product in between two metrices.
- Condition for Dot Product ( firt metrices column, second metrics row shoul be match)

In [85]:
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

In [87]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [88]:
a3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [86]:
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

# 5 - Log and Exponents

In [89]:
np.exp(a1)

array([[5.54062238e+34, 2.58131289e+20, 2.75851345e+33],
       [3.31740010e+39, 1.73927494e+18, 8.65934004e+16],
       [7.20048993e+10, 2.90488497e+13, 2.64891221e+10]])

# 6 - Round / Floor/ Ceil

In [91]:
np.random.random((2,3))

array([[0.85019156, 0.46976082, 0.29438947],
       [0.58474044, 0.82941488, 0.62510163]])

In [92]:
np.round(np.random.random((2,3))* 100) # round off

array([[ 44.,  56.,   0.],
       [ 80., 100.,  59.]])

In [93]:
np.floor(np.random.random((2,3))* 100) # sent forward

array([[67., 84., 62.],
       [29., 81.,  5.]])

In [94]:
np.ceil(np.random.random((2,3))* 100) # send backward

array([[92., 72., 36.],
       [58., 69., 91.]])

# Indexing and Slicing of Numpy Array

In [95]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [96]:
a1 # 1 d array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [97]:
a2 # 2 d array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [98]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [99]:
a1[-1] # fetching last item

9

In [102]:
a1[-5:-2]

array([5, 6, 7])

In [103]:
a2[1,2] # first row second column item will fetch

6

In [104]:
a2[1,0] # first row zero column item will fetch in this matrix

4

In [105]:
a3[0][1]

array([2, 3])

In [107]:
a3[0][1][1] # in zero row , first column, first item 

3

In [109]:
a3[0][1][0]

2

In [110]:
a3[0][0][0]

0

In [111]:
a3[1][0][1]

5

In [112]:
# now will do slicing

In [113]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [115]:
a1[2:5] # first include last not. index given for fetchin item


array([2, 3, 4])

In [116]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [118]:
a2[1][1:3] # first row , first and second item will fetch

array([5, 6])

In [120]:
a2[:,2] # fetching entire row with second column

array([ 2,  6, 10])

In [121]:
a2[1:, 1:3]

array([[ 5,  6],
       [ 9, 10]])

In [123]:
a2[::2, ::3]

array([[ 0,  3],
       [ 8, 11]])

In [134]:
a2[::2, 1::2] # fetching first and third row and one onwards column with 2 jumps. 

array([[ 1,  3],
       [ 9, 11]])

In [135]:
a2[1]

array([4, 5, 6, 7])

In [138]:
a2[1,::3]

array([4, 7])

In [139]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [140]:
a2[:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [142]:
a2[:2,1::2]

array([[1, 3],
       [5, 7]])

In [145]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [146]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [149]:
a3[1][0][1]

10

In [152]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [153]:
a3[0,1,:]

array([3, 4, 5])

In [155]:
a3[1,:,1]

array([10, 13, 16])

In [157]:
a3[1,1]

array([12, 13, 14])

In [160]:
a3[0:, 0,::2]

array([[ 0,  2],
       [ 9, 11],
       [18, 20]])

In [159]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

# ITERATING

In [162]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [163]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [164]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [165]:
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [167]:
for i in a2:
    print(i) # in 2d it will print entire row in one line

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [169]:
for i in a3:
    print(i) # in 3d it will print in 2d array

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


# for iterating over individual item - np.nditer()

In [171]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


# RESHAPING
- 1- reshape
- 2- ravel
- 3- transpose

## Transpose

In [172]:
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [173]:
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [174]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [175]:
a3.T

array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

### 

## Ravel - convert any kind of dimension in one dimension

In [176]:
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

# Stacking
- use when we collect data from different different platform so with horizontal, vertical stacking we can add all 
data to convert in one data. 
- conditon of stacking is shape should be same.

In [187]:
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)

In [189]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [190]:
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# Splitting
- it just the opposite of stacking
- when we want to divivde data branchwise or any other use

# horizontal splitting

In [191]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [192]:
np.hsplit(a4, 2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [195]:
np.hsplit(a4, 4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

# vertical splitting

In [196]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]

### 

### 

### 

### 